config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development? || Rails.env.staging?
    get '/sandbox' => 'sandbox#index'
    get '/sandbox/*template' => 'sandbox#show'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_for :organizations, class_name: 'User',
                             controllers: {
                               registrations: 'organizations/registrations',
                               sessions: 'devise/sessions'
                             },
                             skip: [:omniauth_callbacks]

  devise_scope :organization do
    get 'organizations/sign_up/success', to: 'organizations/registrations#success'
  end

  devise_scope :user do
    patch '/user/confirmation', to: 'users/confirmations#update', as: :update_user_confirmation
    get '/user/registrations/check_username', to: 'users/registrations#check_username'
    get 'users/sign_up/success', to: 'users/registrations#success'
    get 'users/registrations/delete_form', to: 'users/registrations#delete_form'
    delete 'users/registrations', to: 'users/registrations#delete'
    get :finish_signup, to: 'users/registrations#finish_signup'
    patch :do_finish_signup, to: 'users/registrations#do_finish_signup'
  end

  root 'welcome#index'
  get '/welcome', to: 'welcome#welcome'
  get '/cuentasegura', to: 'welcome#verification', as: :cuentasegura

  get '/consul.json', to: "installation#details"

  resources :debates do
    member do
      post :vote
      put :flag
      put :unflag
      put :mark_featured
      put :unmark_featured
    end
    collection do
      get :map
      get :suggest
    end
  end

  resources :proposals do
    member do
      post :vote
      post :vote_featured
      post :approve
      post :archive
      put :flag
      put :unflag
      get :retire_form
      get :share
      patch :retire
    end
    collection do
      get :map
      get :suggest
      get :summary
      get :approved
      get 'approved/:stage', action: 'approved', as: :approved_stage 
    end
  end

  resources :comments, only: [:create, :show], shallow: true do
    member do
      post :vote
      put :flag
      put :unflag
    end
  end

  resources :budgets, only: [:show, :index] do
    resources :groups, controller: "budgets/groups", only: [:show]
    resources :investments, controller: "budgets/investments", only: [:index, :new, :create, :show, :destroy] do
      member do
        post :vote
      end
      collection { get :suggest }
    end
    resource :ballot, only: :show, controller: "budgets/ballots" do
      resources :lines, controller: "budgets/ballot/lines", only: [:create, :destroy]
    end
    resource :results, only: :show, controller: "budgets/results"
  end

  scope '/participatory_budget' do
    resources :spending_proposals, only: [:index, :new, :create, :show, :destroy], path: 'investment_projects' do
      post :vote, on: :member
    end
  end

  resources :follows, only: [:create, :destroy]

  resources :documents, only: [:destroy]

  resources :images, only: [:destroy]

  resources :direct_uploads, only: [:create]
  delete "direct_uploads/destroy", to: "direct_uploads#destroy", as: :direct_upload_destroy

  resources :stats, only: [:index]

  resources :legacy_legislations, only: [:show], path: 'legislations'

  resources :annotations do
    get :search, on: :collection
  end

  resources :polls, only: [:show, :index] do
    member do
      get :stats
      get :results
    end
    resources :questions, controller: 'polls/questions', shallow: true do
      post :answer, on: :member
    end
  end

  namespace :legislation do
    resources :processes, only: [:index, :show] do
      member do
        get :debate
        get :draft_publication
        get :allegations
        get :result_publication
        get :proposals
      end
      resources :questions, only: [:show] do
        resources :answers, only: [:create]
      end
      resources :proposals do
        member do
          post :vote
          put :flag
          put :unflag
        end
        collection do
          get :map
          get :suggest
        end
      end
      resources :draft_versions, only: [:show] do
        get :go_to_version, on: :collection
        get :changes
        resources :annotations do
          get :search, on: :collection
          get :comments
          post :new_comment
        end
      end
    end
  end

  resources :users, only: [:show] do
    resources :direct_messages, only: [:new, :create, :show]
  end

  resource :account, controller: "account", only: [:show, :update, :delete] do
    get :erase, on: :collection
  end

  resources :notifications, only: [:index, :show] do
    put :mark_all_as_read, on: :collection
  end

  resources :proposal_notifications, only: [:new, :create, :show]

  resource :verification, controller: "verification", only: [:show]

  resources :communities, only: [:show] do
    resources :topics
  end

  scope module: :verification do
    resource :residence, controller: "residence", only: [:new, :create]
    resource :sms, controller: "sms", only: [:new, :create, :edit, :update]
    resource :verified_user, controller: "verified_user", only: [:show]
    resource :email, controller: "email", only: [:new, :show, :create]
    resource :letter, controller: "letter", only: [:new, :create, :show, :edit, :update]
  end

  resources :tags do
    collection do
      get :suggest
    end
  end

  namespace :admin do
    root to: "dashboard#index"
    resources :organizations, only: :index do
      get :search, on: :collection
      member do
        put :verify
        put :reject
      end
    end

    resources :hidden_users, only: [:index, :show] do
      member do
        put :restore
        put :confirm_hide
      end
    end

    resources :debates, only: :index do
      member do
        put :restore
        put :confirm_hide
      end
    end

    resources :proposals, only: :index do
      member do
        put :restore
        put :confirm_hide
      end
    end

    resources :spending_proposals, only: [:index, :show, :edit, :update] do
      member do
        patch :assign_admin
        patch :assign_valuators
      end

      get :summary, on: :collection
    end

    resources :budgets do
      member do
        put :calculate_winners
      end

      resources :budget_groups do
        resources :budget_headings do
        end
      end

      resources :budget_investments, only: [:index, :show, :edit, :update] do
        resources :budget_investment_milestones
        member { patch :toggle_selection }
      end
    end

    resources :signature_sheets, only: [:index, :new, :create, :show]

    resources :banners, only: [:index, :new, :create, :edit, :update, :destroy] do
      collection { get :search}
    end

    resources :comments, only: :index do
      member do
        put :restore
        put :confirm_hide
      end
    end

    resources :tags, only: [:index, :create, :update, :destroy]
    resources :officials, only: [:index, :edit, :update, :destroy] do
      get :search, on: :collection
    end

    resources :settings, only: [:index, :update]
    put :update_map, to: "settings#update_map"

    resources :moderators, only: [:index, :create, :destroy] do
      get :search, on: :collection
    end

    resources :valuators, only: [:index, :create, :destroy] do
      get :search, on: :collection
      get :summary, on: :collection
    end

    resources :managers, only: [:index, :create, :destroy] do
      get :search, on: :collection
    end

    resources :administrators, only: [:index, :create, :destroy] do
      get :search, on: :collection
    end

    resources :users, only: [:index, :show]

    scope module: :poll do
      resources :polls do
        get :booth_assignments, on: :collection
        patch :add_question, on: :member

        resources :booth_assignments, only: [:index, :show, :create, :destroy] do
          get :search_booths, on: :collection
          get :manage, on: :collection
        end

        resources :officer_assignments, only: [:index, :create, :destroy] do
          get :search_officers, on: :collection
          get :by_officer, on: :collection
        end

        resources :recounts, only: :index
        resources :results, only: :index
      end

      resources :officers do
        get :search, on: :collection
      end

      resources :booths do
        get :available, on: :collection

        resources :shifts do
          get :search_officers, on: :collection
        end
      end

      resources :questions, shallow: true do
        resources :answers, except: [:index, :destroy], controller: 'questions/answers', shallow: true do
          resources :images, controller: 'questions/answers/images'
          resources :videos, controller: 'questions/answers/videos'
          get :documents, to: 'questions/answers#documents'
        end
        post '/answers/order_answers', to: 'questions/answers#order_answers'
      end
    end

    resources :verifications, controller: :verifications, only: :index do
      get :search, on: :collection
    end

    resource :activity, controller: :activity, only: :show
    resources :newsletters, only: :index do
      get :users, on: :collection
    end
    resource :stats, only: :show do
      get :proposal_notifications, on: :collection
      get :direct_messages, on: :collection
      get :polls, on: :collection
    end

    namespace :legislation do
      resources :processes do
        resources :questions
        resources :proposals
        resources :draft_versions
      end
    end

    namespace :api do
      resource :stats, only: :show
    end

    resources :geozones, only: [:index, :new, :create, :edit, :update, :destroy]

    namespace :site_customization do
      resources :pages, except: [:show]

app/models/budget/ballot.rb
class Budget
  class Ballot < ActiveRecord::Base
    belongs_to :user
    belongs_to :budget

    has_many :lines, dependent: :destroy
    has_many :investments, through: :lines
    has_many :groups, -> { uniq }, through: :lines
    has_many :headings, -> { uniq }, through: :groups

    def add_investment(investment)
      lines.create(investment: investment).persisted?
    end

    def total_amount_spent
      investments.sum(:price).to_i
    end

    def amount_spent(heading)
      investments.by_heading(heading.id).sum(:price).to_i
    end

    def formatted_amount_spent(heading)
      budget.formatted_amount(amount_spent(heading))
    end

    def amount_available(heading)
      budget.heading_price(heading) - amount_spent(heading)
    end

    def formatted_amount_available(heading)
      budget.formatted_amount(amount_available(heading))
    end

    def has_lines_in_group?(group)
      groups.include?(group)
    end

    def wrong_budget?(heading)
      heading.budget_id != budget_id
    end

    def different_heading_assigned?(heading)
      other_heading_ids = heading.group.heading_ids - [heading.id]
      lines.where(heading_id: other_heading_ids).exists?
    end

    def valid_heading?(heading)
      !wrong_budget?(heading) && !different_heading_assigned?(heading)
    end

    def has_lines_with_no_heading?
      investments.no_heading.count > 0
    end

    def has_lines_with_heading?
      heading_id.present?
    end

    def has_lines_in_heading?(heading)
      investments.by_heading(heading.id).any?
    end

    def has_investment?(investment)
      investment_ids.include?(investment.id)
    end

    def heading_for_group(group)
      return nil unless has_lines_in_group?(group)
      investments.where(group: group).first.heading
    end

  end
end

app/controllers/admin/budgets_controller.rb
class Admin::BudgetsController < Admin::BaseController
  include FeatureFlags
  feature_flag :budgets

  has_filters %w{current finished}, only: :index

  load_and_authorize_resource

  def index
    @budgets = Budget.send(@current_filter).order(created_at: :desc).page(params[:page])
  end

  def show
    @budget = Budget.includes(groups: :headings).find(params[:id])
  end

  def new; end

  def edit; end

  def calculate_winners
    return unless @budget.balloting_process?
    @budget.headings.each { |heading| Budget::Result.new(@budget, heading).delay.calculate_winners }
    redirect_to admin_budget_budget_investments_path(budget_id: @budget.id, filter: 'winners'),
                notice: I18n.t("admin.budgets.winners.calculated")
  end

  def update
    if @budget.update(budget_params)
      redirect_to admin_budget_path(@budget), notice: t('admin.budgets.update.notice')
    else
      render :edit
    end
  end

  def create
    @budget = Budget.new(budget_params)
    if @budget.save
      redirect_to admin_budget_path(@budget), notice: t('admin.budgets.create.notice')
    else
      render :new
    end
  end

  private

    def budget_params
      descriptions = Budget::PHASES.map{|p| "description_#{p}"}.map(&:to_sym)
      valid_attributes = [:name, :phase, :currency_symbol] + descriptions
      params.require(:budget).permit(*valid_attributes)
    end

end

app/controllers/admin/poll/results_controller.rb
class Admin::Poll::ResultsController < Admin::Poll::BaseController
  before_action :load_poll

  def index
    @partial_results = @poll.partial_results
  end

  private

    def load_poll
      @poll = ::Poll.includes(:questions).find(params[:poll_id])
    end
end

app/controllers/budgets/ballot/lines_controller.rb
module Budgets
  module Ballot
    class LinesController < ApplicationController
      before_action :authenticate_user!
      #before_action :ensure_final_voting_allowed
      before_action :load_budget
      before_action :load_ballot
      before_action :load_tag_cloud
      before_action :load_categories
      before_action :load_investments
      before_action :load_ballot_referer

      load_and_authorize_resource :budget
      load_and_authorize_resource :ballot, class: "Budget::Ballot", through: :budget
      load_and_authorize_resource :line, through: :ballot, find_by: :investment_id, class: "Budget::Ballot::Line"

      def create
        load_investment
        load_heading

        @ballot.add_investment(@investment)
      end

      def destroy
        @investment = @line.investment
        load_heading

        @line.destroy
        load_investments
      end

      private

        def ensure_final_voting_allowed
          return head(:forbidden) unless @budget.balloting?
        end

        def line_params
          params.permit(:investment_id, :budget_id)
        end

        def load_budget
          @budget = Budget.find(params[:budget_id])
        end

        def load_ballot
          @ballot = Budget::Ballot.where(user: current_user, budget: @budget).first_or_create
        end

        def load_investment
          @investment = Budget::Investment.find(params[:investment_id])
        end

        def load_investments
          if params[:investments_ids].present?
            @investment_ids = params[:investments_ids]
            @investments = Budget::Investment.where(id: params[:investments_ids])
          end
        end

        def load_heading
          @heading = @investment.heading
        end

        def load_tag_cloud
          @tag_cloud = TagCloud.new(Budget::Investment, params[:search])
        end

        def load_categories
          @categories = ActsAsTaggableOn::Tag.category.order(:name)
        end

        def load_ballot_referer
          @ballot_referer = session[:ballot_referer]
        end

    end
  end
end

app/controllers/budgets/ballots_controller.rb
module Budgets
  class BallotsController < ApplicationController
    before_action :authenticate_user!
    load_and_authorize_resource :budget
    before_action :load_ballot
    after_action :store_referer, only: [:show]

    def show
      authorize! :show, @ballot
      session[:ballot_referer] = request.referer
      render template: "budgets/ballot/show"
    end

    private

      def load_ballot
        query = Budget::Ballot.where(user: current_user, budget: @budget)
        @ballot = @budget.balloting? ? query.first_or_create : query.first_or_initialize
      end

      def store_referer
        session[:ballot_referer] = request.referer
      end

  end
end

app/controllers/budgets/groups_controller.rb
module Budgets
  class GroupsController < ApplicationController
    load_and_authorize_resource :budget
    load_and_authorize_resource :group, class: "Budget::Group"

    before_action :set_default_budget_filter, only: :show
    has_filters %w{not_unfeasible feasible unfeasible unselected selected}, only: [:show]

    def show
    end

  end
end

app/controllers/budgets/results_controller.rb
module Budgets
  class ResultsController < ApplicationController
    before_action :load_budget
    before_action :load_heading

    load_and_authorize_resource :budget

    def show
      authorize! :read_results, @budget
      @investments = Budget::Result.new(@budget, @heading).investments
    end

    private

      def load_budget
        @budget = Budget.find_by(id: params[:budget_id])
      end

      def load_heading
        @heading = if params[:heading_id].present?
                     @budget.headings.find(params[:heading_id])
                   else
                     @budget.headings.first
                   end
      end

  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  include FeatureFlags
  feature_flag :budgets

  load_and_authorize_resource
  before_action :set_default_budget_filter, only: :show
  has_filters %w{not_unfeasible feasible unfeasible unselected selected}, only: :show

  respond_to :html, :js

  def show
  end

  def index
    @budgets = @budgets.order(:created_at)
  end

end

app/views/budgets/results/_results_table.html.erb
<div class="small-12 medium-9 large-10 column <%= results_type == :compatible ? 'success' : 'js-discarded' %>"
     style="<%= results_type != :compatible ? 'display: none' : '' %>"
     id="<%= results_type %>-container">

  <h4 class="inline-block">
    <%= title %>
  </h4>

  <table id="budget-investments-<%= results_type %>" class="table-for-mobile">
    <thead>
      <tr>
        <th scope="col">
          <%= t("budgets.results.spending_proposal") %>
        </th>
        <th scope="col" class="text-center">
          <%= t("budgets.results.ballot_lines_count") %>
        </th>
        <th scope="col" class="text-center">
          <%= t("budgets.results.price") %>
        </th>
        <% if results_type == :compatible %>
          <th scope="col" class="text-right">
            <small><%= t("budgets.results.amount_available") %></small><br>
            <%= format_price(heading_price) %><br>
          </th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% amount_available = heading_price %>
      <% investments.each do |investment| %>
          <tr id="<%= dom_id(investment) %>"
              class="budget-investments <%= investment.winner? ? 'success' : 'js-discarded' %>"
              style="<%= investment.winner? ? '' : 'display: none' %>">
            <td>
              <% if investment.winner? %>
                <span class="icon-check">
                  <span class="show-for-sr">
                    <%= t("budgets.results.accepted") %>
                  </span>
                </span>
              <% else %>
                <span class="icon-x delete">
                  <span class="show-for-sr">
                    <%= t("budgets.results.discarded") %>
                  </span>
                </span>
              <% end %>
              <%= link_to investment.title, budget_investment_path(@budget, investment) %>
            </td>
            <td class="text-center">
              <%= investment.ballot_lines_count %>
            </td>
            <td class="text-center">
              <%= format_price investment.price %>
            </td>
            <% if results_type == :compatible %>
              <td class="small text-right"
                  title="<%= format_price(amount_available) %> - <%= format_price(investment.price) %>">
                  <%= format_price amount_available - investment.price %>
                  <% amount_available -= investment.price if investment.winner? %>
              </td>
            <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/budgets/results/show.html.erb
<% provide :title, t("budgets.results.page_title", budget: @budget.name) %>
<% content_for :meta_description do %><%= @budget.description_finished %><% end %>
<% provide :social_media_meta_tags do %>
<%= render "shared/social_media_meta_tags",
            social_url: budget_results_url(@budget),
            social_title: @budget.name,
            social_description: @budget.description_finished %>
<% end %>
<% content_for :canonical do %>
  <%= render "shared/canonical", href: budget_results_url(@budget) %>
<% end %>

<div class="budgets-stats">
  <div class="expanded no-margin-top padding header">
    <div class="row">
      <div class="small-12 column text-center">
        <%= back_link_to budget_path(@budget) %>
        <h1 class="title"><%= t("budgets.results.heading") %><br><%= @budget.name %></h1>
      </div>
    </div>
  </div>
</div>

<div class="row margin-top">
  <div class="small-12 column">
    <ul class="tabs">
      <li class="tabs-title is-active">
        <span class="show-for-sr"><%= t("shared.you_are_in") %></span>
        <%= link_to t("budgets.results.link"), budget_results_path(@budget), class: "is-active"  %>
      </li>
      <li class="tabs-title">
        <%# link_to t("budgets.stats.link"), budget_stats_path(@budget)%>
      </li>
    </ul>
  </div>
</div>

<div class="row">
  <div class="small-12 medium-3 large-2 column">
    <h3 class="margin-bottom">
      <%= t("budgets.results.heading_selection_title") %>
    </h3>
    <ul class="menu vertical no-margin-top no-padding-top">


      <% @budget.headings.order('id ASC').each do |heading| %>
        <li>
          <%= link_to heading.name,
                      budget_results_path(@budget, heading_id: heading.to_param),
                      class: heading.to_param == @heading.to_param ? 'active' : '' %>
        </li>
      <% end %>
    </ul>
  </div>

  <span class="float-right"><%= link_to t("budgets.results.show_all_link"), "#", class: "js-toggle-link button hollow margin-bottom", data: {'toggle-selector' => '.js-discarded', 'toggle-text' => t("budgets.results.hide_discarded_link")} %></span>


  <%= render 'results_table', results_type: :compatible,
                              title: @heading.name,
                              heading_price: @heading.price,
                              investments: @investments.compatible %>

  <% if @investments.incompatible.present? %>
    <%= render 'results_table', results_type: :incompatible,
                                title: t("budgets.results.incompatibles"),
                                heading_price: @heading.price,
                                investments: @investments.incompatible %>
  <% end %>
</div>