config/routes.rb
  delete "direct_uploads/destroy", to: "direct_uploads#destroy", as: :direct_upload_destroy

  resources :stats, only: [:index]

  resources :legacy_legislations, only: [:show], path: 'legislations'

  resources :annotations do
    get :search, on: :collection
  end

  resources :polls, only: [:show, :index] do
    member do
      get :stats
      get :results
    end
    resources :questions, controller: 'polls/questions', shallow: true do
      post :answer, on: :member
    end
  end

  namespace :legislation do
    resources :processes, only: [:index, :show] do
      member do
        get :debate
        get :draft_publication
        get :allegations
        get :result_publication
        get :proposals
      end
      resources :questions, only: [:show] do
        resources :answers, only: [:create]
      end
      resources :proposals do
        member do
          post :vote
          put :flag
          put :unflag
        end
        collection do
          get :map
          get :suggest
        end
      end
      resources :draft_versions, only: [:show] do
        get :go_to_version, on: :collection
        get :changes
        resources :annotations do
          get :search, on: :collection
          get :comments
          post :new_comment
        end
      end
    end
  end

  resources :users, only: [:show] do
    resources :direct_messages, only: [:new, :create, :show]
  end

  resource :account, controller: "account", only: [:show, :update, :delete] do
    get :erase, on: :collection
  end

  resources :notifications, only: [:index, :show] do
    put :mark_all_as_read, on: :collection
  end

  resources :proposal_notifications, only: [:new, :create, :show]

  resource :verification, controller: "verification", only: [:show]

  resources :communities, only: [:show] do
    resources :topics
  end

  scope module: :verification do
    resource :residence, controller: "residence", only: [:new, :create]
    resource :sms, controller: "sms", only: [:new, :create, :edit, :update]
    resource :verified_user, controller: "verified_user", only: [:show]
    resource :email, controller: "email", only: [:new, :show, :create]
    resource :letter, controller: "letter", only: [:new, :create, :show, :edit, :update]
  end

  resources :tags do
    collection do
      get :suggest
    end
  end

  namespace :admin do
    root to: "dashboard#index"
    resources :organizations, only: :index do
      get :search, on: :collection
      member do
        put :verify
        put :reject
      end
    end

    resources :hidden_users, only: [:index, :show] do
      member do
        put :restore
        put :confirm_hide
      end
    end

    resources :debates, only: :index do
      member do
        put :restore
        put :confirm_hide
      end
    end

    resources :proposals, only: :index do
      member do
        put :restore
        put :confirm_hide
      end
    end

    resources :spending_proposals, only: [:index, :show, :edit, :update] do
      member do
        patch :assign_admin
        patch :assign_valuators
      end

      get :summary, on: :collection
    end

    resources :budgets do
      member do
        put :calculate_winners
      end

      resources :budget_groups do
        resources :budget_headings do
        end
      end

      resources :budget_investments, only: [:index, :show, :edit, :update] do
        resources :budget_investment_milestones
        member { patch :toggle_selection }
      end
    end

    resources :signature_sheets, only: [:index, :new, :create, :show]

    resources :banners, only: [:index, :new, :create, :edit, :update, :destroy] do
      collection { get :search}
    end

    resources :comments, only: :index do
      member do
        put :restore
        put :confirm_hide
      end
    end

    resources :tags, only: [:index, :create, :update, :destroy]
    resources :officials, only: [:index, :edit, :update, :destroy] do
      get :search, on: :collection
    end

    resources :settings, only: [:index, :update]
    put :update_map, to: "settings#update_map"

    resources :moderators, only: [:index, :create, :destroy] do
      get :search, on: :collection
    end

    resources :valuators, only: [:index, :create, :destroy] do
      get :search, on: :collection
      get :summary, on: :collection
    end

    resources :managers, only: [:index, :create, :destroy] do
      get :search, on: :collection
    end

    resources :administrators, only: [:index, :create, :destroy] do
      get :search, on: :collection
    end

    resources :users, only: [:index, :show]

    scope module: :poll do
      resources :polls do
        get :booth_assignments, on: :collection
        patch :add_question, on: :member

        resources :booth_assignments, only: [:index, :show, :create, :destroy] do
          get :search_booths, on: :collection
          get :manage, on: :collection
        end

        resources :officer_assignments, only: [:index, :create, :destroy] do
          get :search_officers, on: :collection
          get :by_officer, on: :collection
        end

        resources :recounts, only: :index
        resources :results, only: :index
      end

      resources :officers do
        get :search, on: :collection
      end

      resources :booths do
        get :available, on: :collection

        resources :shifts do
          get :search_officers, on: :collection
        end
      end

      resources :questions, shallow: true do
        resources :answers, except: [:index, :destroy], controller: 'questions/answers', shallow: true do
          resources :images, controller: 'questions/answers/images'
          resources :videos, controller: 'questions/answers/videos'
          get :documents, to: 'questions/answers#documents'
        end
        post '/answers/order_answers', to: 'questions/answers#order_answers'
      end
    end

    resources :verifications, controller: :verifications, only: :index do
      get :search, on: :collection
    end

    resource :activity, controller: :activity, only: :show
    resources :newsletters, only: :index do
      get :users, on: :collection
    end
    resource :stats, only: :show do
      get :proposal_notifications, on: :collection
      get :direct_messages, on: :collection
      get :polls, on: :collection
    end

    namespace :legislation do
      resources :processes do
        resources :questions
        resources :proposals
        resources :draft_versions
      end
    end

    namespace :api do
      resource :stats, only: :show
    end

    resources :geozones, only: [:index, :new, :create, :edit, :update, :destroy]

    namespace :site_customization do
      resources :pages, except: [:show]
      resources :images, only: [:index, :update, :destroy]
      resources :content_blocks, except: [:show]
    end
  end

  namespace :moderation do
    root to: "dashboard#index"

    resources :users, only: :index do
      member do
        put :hide
        put :hide_in_moderation_screen
      end
    end

    resources :debates, only: :index do
      put :hide, on: :member
      put :moderate, on: :collection
    end

    resources :proposals, only: :index do
      put :hide, on: :member
      put :moderate, on: :collection
    end

    resources :comments, only: :index do
      put :hide, on: :member
      put :moderate, on: :collection
    end
  end

  namespace :valuation do
    root to: "budgets#index"

    resources :spending_proposals, only: [:index, :show, :edit] do
      patch :valuate, on: :member
    end

    resources :budgets, only: :index do
      resources :budget_investments, only: [:index, :show, :edit] do
        patch :valuate, on: :member
      end
    end
  end

  namespace :management do
    root to: "dashboard#index"

    resources :document_verifications, only: [:index, :new, :create] do
      post :check, on: :collection
    end

    resources :email_verifications, only: [:new, :create]

    resources :user_invites, only: [:new, :create]

    resources :users, only: [:new, :create] do
      collection do
        delete :logout
        delete :erase
      end
    end

    resource :account, controller: "account", only: [:show]

    get 'sign_in', to: 'sessions#create', as: :sign_in

    resource :session, only: [:create, :destroy]
    resources :proposals, only: [:index, :new, :create, :show] do
      post :vote, on: :member
      get :print, on: :collection
    end

    resources :spending_proposals, only: [:index, :new, :create, :show] do
      post :vote, on: :member
      get :print, on: :collection
    end

    resources :budgets, only: :index do
      collection do
        get :create_investments
        get :support_investments
        get :print_investments
      end
      resources :investments, only: [:index, :new, :create, :show, :destroy], controller: 'budgets/investments' do
        post :vote, on: :member
        get :print, on: :collection
      end
    end
  end

  namespace :officing do
    resources :polls, only: [:index] do
      get :final, on: :collection

      resources :results, only: [:new, :create, :index]
    end
    resource :residence, controller: "residence", only: [:new, :create]
    resources :voters, only: [:new, :create]
    root to: "dashboard#index"
  end

  resources :related_contents, only: [:create]

  # GraphQL
  get '/graphql', to: 'graphql#query'
  post '/graphql', to: 'graphql#query'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'

  # more info pages
  get 'more-information',                     to: 'pages#show', id: 'more_info/index',                as: 'more_info'
  get 'more-information/how-to-use',          to: 'pages#show', id: 'more_info/how_to_use/index',     as: 'how_to_use'
  get 'more-information/faq',                 to: 'pages#show', id: 'more_info/faq/index',            as: 'faq'

  # static pages

app/controllers/management/account_controller.rb
class Management::AccountController < Management::BaseController

  before_action :only_verified_users

  def show
  end

  private

    def only_verified_users
      check_verified_user t("management.account.alert.unverified_user")
    end

end

app/controllers/management/base_controller.rb
class Management::BaseController < ActionController::Base
  layout 'management'

  before_action :verify_manager
  before_action :set_locale

  helper_method :managed_user

  private

    def verify_manager
      raise ActionController::RoutingError.new('Not Found') if current_manager.blank?
    end

    def current_manager
      session[:manager]
    end

    def current_user
      managed_user
    end

    def managed_user
      @managed_user ||= Verification::Management::ManagedUser.find(session[:document_type], session[:document_number])
    end

    def check_verified_user(alert_msg)
      unless managed_user.level_two_or_three_verified?
        redirect_to management_document_verifications_path, alert: alert_msg
      end
    end

    def set_locale
      if params[:locale] && I18n.available_locales.include?(params[:locale].to_sym)
        session[:locale] = params[:locale]
      end

      session[:locale] ||= I18n.default_locale

      I18n.locale = session[:locale]
    end

end

app/controllers/management/budgets/investments_controller.rb
class Management::Budgets::InvestmentsController < Management::BaseController

  load_resource :budget
  load_resource :investment, through: :budget, class: 'Budget::Investment'

  before_action :only_verified_users, except: :print
  before_action :load_heading, only: [:index, :show, :print]

  def index
    @investments = @investments.apply_filters_and_search(@budget, params).page(params[:page])
    load_investment_votes(@investments)
  end

  def new
    load_categories
  end

  def create
    @investment.terms_of_service = "1"
    @investment.author = managed_user

    if @investment.save
      notice = t('flash.actions.create.notice', resource_name: Budget::Investment.model_name.human, count: 1)
      redirect_to management_budget_investment_path(@budget, @investment), notice: notice
    else
      render :new
    end
  end

  def show
    load_investment_votes(@investment)
  end

  def vote
    @investment.register_selection(managed_user)
    load_investment_votes(@investment)
    respond_to do |format|
      format.html { redirect_to management_budget_investments_path(heading_id: @investment.heading.id) }
      format.js
    end
  end

  def print
    @investments = @investments.apply_filters_and_search(@budget, params).order(cached_votes_up: :desc).for_render.limit(15)
    load_investment_votes(@investments)
  end

  private

    def load_investment_votes(investments)
      @investment_votes = managed_user ? managed_user.budget_investment_votes(investments) : {}
    end

    def investment_params
      params.require(:budget_investment).permit(:title, :description, :external_url, :heading_id, :tag_list, :organization_name, :location)
    end

    def only_verified_users
      check_verified_user t("management.budget_investments.alert.unverified_user")
    end

    def load_heading
      @heading = @budget.headings.find(params[:heading_id]) if params[:heading_id].present?
    end

    def load_categories
      @categories = ActsAsTaggableOn::Tag.category.order(:name)
    end

end

app/controllers/management/budgets_controller.rb
class Management::BudgetsController < Management::BaseController
  include FeatureFlags
  include HasFilters
  feature_flag :budgets

  before_action :only_verified_users, except: :print_investments

  def create_investments
    @budgets = Budget.accepting.order(created_at: :desc).page(params[:page])

    if current_manager_administrator?
      @budgets += Budget.reviewing.order(created_at: :desc) +
                  Budget.selecting.order(created_at: :desc)
    end
  end

  def support_investments
    @budgets = Budget.selecting.order(created_at: :desc).page(params[:page])
  end

  def print_investments
    @budgets = Budget.current.order(created_at: :desc).page(params[:page])
  end

  private

    def only_verified_users
      check_verified_user t("management.budget_investments.alert.unverified_user")
    end

    def current_manager_administrator?
      session[:manager]["login"].match("admin")
    end

end

app/controllers/management/dashboard_controller.rb
class Management::DashboardController < Management::BaseController

  def index
  end

end

app/controllers/management/document_verifications_controller.rb
class Management::DocumentVerificationsController < Management::BaseController

  before_action :clean_document_number, only: :check
  before_action :set_document, only: :check

  def index
    @document_verification = Verification::Management::Document.new
  end

  def check
    @document_verification = Verification::Management::Document.new(document_verification_params)

    if @document_verification.valid?
      if @document_verification.verified?
        render :verified
      elsif @document_verification.user?
        render :new
      elsif @document_verification.in_census?
        redirect_to new_management_email_verification_path(email_verification: document_verification_params)
      else
        render :invalid_document
      end
    else
      render :index
    end
  end

  def create
    @document_verification = Verification::Management::Document.new(document_verification_params)
    @document_verification.verify
    render :verified
  end

  private

    def document_verification_params
      params.require(:document_verification).permit(:document_type, :document_number)
    end

    def set_document
      session[:document_type] = params[:document_verification][:document_type]
      session[:document_number] = params[:document_verification][:document_number]
    end

    def clean_document_number
      return if params[:document_verification][:document_number].blank?
      params[:document_verification][:document_number] = params[:document_verification][:document_number].gsub(/[^a-z0-9]+/i, "").upcase
    end

end

app/controllers/management/email_verifications_controller.rb
class Management::EmailVerificationsController < Management::BaseController

  def new
    @email_verification = Verification::Management::Email.new(email_verification_params)
  end

  def create
    @email_verification = Verification::Management::Email.new(email_verification_params)

    if @email_verification.save
      render :sent
    else
      render :new
    end
  end

  private

    def email_verification_params
      params.require(:email_verification).permit(:document_type, :document_number, :email)
    end

end

app/controllers/management/sessions_controller.rb
require "manager_authenticator"

class Management::SessionsController < ActionController::Base

  def create
    destroy_session
    if admin? || manager? || authenticated_manager?
      redirect_to management_root_path
    else
      raise CanCan::AccessDenied
    end
  end

  def destroy
    destroy_session
    redirect_to root_path, notice: t("management.sessions.signed_out")
  end

  private

    def destroy_session
      session[:manager] = nil
      session[:document_type] = nil
      session[:document_number] = nil
    end

    def admin?
      if current_user.try(:administrator?)
        session[:manager] = {login: "admin_user_#{current_user.id}"}
      end
    end

    def manager?
      if current_user.try(:manager?)
        session[:manager] = {login: "manager_user_#{current_user.id}"}
      end
    end

    def authenticated_manager?
      manager = ManagerAuthenticator.new(params).auth
      session[:manager] = manager if manager.present?
    end

end

app/views/management/_account_info.html.erb
<% if managed_user.document_number.present? %>
  <section class="small-12 medium-9 column">
    <div class="account-info">

      <%= link_to(t("management.account_info.change_user"), logout_management_users_path, method: :delete, class: 'float-right change-user') %>

      <% if managed_user.level_two_or_three_verified? %>
        <p>
          <%= t("management.account_info.identified_label") %>
        </p>
      <% end %>

      <% if managed_user.username.present? %>
        <p>
          <%= t("management.account_info.username_label") %>
          <strong><%= managed_user.username %></strong>
        </p>
      <% end %>

      <% if managed_user.email.present? %>
        <p>
          <%= t("management.account_info.email_label") %>
          <strong><%= managed_user.email %></strong>
        </p>
      <% end %>

      <p>
        <%= t("management.account_info.document_type_label") %>
        <strong><%= humanize_document_type(managed_user.document_type) %></strong>
      </p>

      <p>
        <%= t("management.account_info.document_number_label") %>
        <strong><%= managed_user.document_number %></strong>
      </p>
    </div>
  </section>
<% end %>

app/views/management/_menu.html.erb
<div class="admin-sidebar">
  <ul id="admin_menu">
    <li <%= "class=active" if controller_name == "document_verifications" ||
                              controller_name == "email_verifications" ||
                              controller_name == "users" %>>
      <%= link_to management_document_verifications_path do %>
        <span class="icon-user"></span>
        <%= t("management.menu.users") %>
      <% end %>
    </li>

    <li <%= "class=active" if controller_name == "account" %>>
      <%= link_to management_account_path do %>
        <span class="icon-user"></span>
        <%= t("management.menu.edit_user_accounts") %>
      <% end %>
    </li>

    <li <%= "class=active" if controller_name == "proposals" && action_name == "new" %>>
      <%= link_to new_management_proposal_path do %>
        <span class="icon-proposals"></span>
        <%= t("management.menu.create_proposal") %>
      <% end %>
    </li>

    <li <%= "class=active" if controller_name == "proposals" && action_name == "index"  %>>
      <%= link_to management_proposals_path do %>
        <span class="icon-like"></span>
        <%= t("management.menu.support_proposals") %>
      <% end %>
    </li>

    <li <%= "class=active" if controller_name == "spending_proposals" && action_name == "new" %>>
      <%= link_to new_management_spending_proposal_path do %>
        <span class="icon-budget"></span>
        <%= t("management.menu.create_spending_proposal") %>
      <% end %>
    </li>

    <li <%= "class=active" if controller_name == "spending_proposals" && action_name == "index" %>>
      <%= link_to management_spending_proposals_path do %>
        <span class="icon-like"></span>
        <%= t("management.menu.support_spending_proposals") %>
      <% end %>
    </li>

    <% if Setting['feature.budgets'] %>
      <li <%= "class=active" if (controller_name == "budget_investments" && action_name == "new") ||
                                (controller_name == "budget" && action_name == 'create_investments') %>>
        <%= link_to create_investments_management_budgets_path do %>
          <span class="icon-budget"></span>
          <%= t("management.menu.create_budget_investment") %>
        <% end %>
      </li>

      <li <%= "class=active" if (controller_name == "budget_investments" && action_name == "index") ||
                                (controller_name == "budget" && action_name == "support_investments")%>>
        <%= link_to support_investments_management_budgets_path do %>
          <span class="icon-like"></span>
          <%= t("management.menu.support_budget_investments") %>
        <% end %>
      </li>

        <li <%= "class=active" if (controller_name == "budget_investments" && action_name == "print") ||
            (controller_name == "budgets" && action_name == "print_investments") %>>
          <%= link_to print_investments_management_budgets_path do %>
              <span class="icon-print"></span>
              <%= t("management.menu.print_budget_investments") %>
          <% end %>
        </li>
    <% end %>

    <li <%= "class=active" if controller_name == "proposals" && action_name == "print" %>>
      <%= link_to print_management_proposals_path do %>
        <span class="icon-print"></span>
        <%= t("management.menu.print_proposals") %>
      <% end %>
    </li>

    <li <%= "class=active" if controller_name == "spending_proposals" && action_name == "print" %>>
      <%= link_to print_management_spending_proposals_path do %>
        <span class="icon-print"></span>
        <%= t("management.menu.print_spending_proposals") %>
      <% end %>
    </li>

    <li>
      <%= link_to new_management_user_invite_path do %>
        <span class="icon-letter"></span>
        <%= t("management.menu.user_invites") %>
      <% end %>
    </li>
  </ul>
</div>

app/views/management/_user_permissions.html.erb
<%
    # Parameters:
    #   message: A string explaining the permissions
    #   permissions: An array of symbols containing the permissions
    #   (can be :debates, :proposal, :support_proposal, :votes)
%>
<div class="user-permissions">

  <p><%= message %></p>

  <ul>
    <% [:debates, :create_proposals, :support_proposals, :vote_proposals].each do |permission| %>
      <li>
        <span class="<%= permissions.include?(permission) ? 'icon-check' : 'icon-x' %>"></span>
        <%= t("management.permissions.#{permission}") %>
      </li>
    <% end %>
  </ul>

</div>