config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development? || Rails.env.staging?
    get '/sandbox' => 'sandbox#index'
    get '/sandbox/*template' => 'sandbox#show'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_for :organizations, class_name: 'User',
                             controllers: {
                               registrations: 'organizations/registrations',
                               sessions: 'devise/sessions'
                             },
                             skip: [:omniauth_callbacks]

  devise_scope :organization do
    get 'organizations/sign_up/success', to: 'organizations/registrations#success'
  end

  devise_scope :user do
    patch '/user/confirmation', to: 'users/confirmations#update', as: :update_user_confirmation
    get '/user/registrations/check_username', to: 'users/registrations#check_username'
    get 'users/sign_up/success', to: 'users/registrations#success'
    get 'users/registrations/delete_form', to: 'users/registrations#delete_form'
    delete 'users/registrations', to: 'users/registrations#delete'
    get :finish_signup, to: 'users/registrations#finish_signup'
    patch :do_finish_signup, to: 'users/registrations#do_finish_signup'
  end

  root 'welcome#index'
  get '/welcome', to: 'welcome#welcome'
  get '/cuentasegura', to: 'welcome#verification', as: :cuentasegura

  get '/consul.json', to: "installation#details"

  resources :debates do
    member do
      post :vote
      put :flag
      put :unflag
      put :mark_featured
      put :unmark_featured
    end
    collection do
      get :map
      get :suggest
    end
  end

  resources :proposals do
    member do
      post :vote
      post :vote_featured
      post :approve
      post :archive
      put :flag
      put :unflag
      get :retire_form
      get :share
      patch :retire
    end
    collection do
      get :map
      get :suggest
      get :summary
      get :approved
      get 'approved/:stage', action: 'approved', as: :approved_stage 
    end
  end

  resources :comments, only: [:create, :show], shallow: true do
    member do
      post :vote
      put :flag
      put :unflag
    end
  end

  resources :budgets, only: [:show, :index] do
    resources :groups, controller: "budgets/groups", only: [:show]
    resources :investments, controller: "budgets/investments", only: [:index, :new, :create, :show, :destroy] do
      member do
        post :vote
      end
      collection { get :suggest }
    end
    resource :ballot, only: :show, controller: "budgets/ballots" do
      resources :lines, controller: "budgets/ballot/lines", only: [:create, :destroy]
    end
    resource :results, only: :show, controller: "budgets/results"
  end

  scope '/participatory_budget' do
    resources :spending_proposals, only: [:index, :new, :create, :show, :destroy], path: 'investment_projects' do
      post :vote, on: :member
    end
  end

  resources :follows, only: [:create, :destroy]

  resources :documents, only: [:destroy]

  resources :images, only: [:destroy]

  resources :direct_uploads, only: [:create]
  delete "direct_uploads/destroy", to: "direct_uploads#destroy", as: :direct_upload_destroy

  resources :stats, only: [:index]

  resources :legacy_legislations, only: [:show], path: 'legislations'

  resources :annotations do
    get :search, on: :collection
  end

  resources :polls, only: [:show, :index] do
    member do
      get :stats
      get :results
    end
    resources :questions, controller: 'polls/questions', shallow: true do
      post :answer, on: :member
    end
  end

  namespace :legislation do
    resources :processes, only: [:index, :show] do
      member do
        get :debate
        get :draft_publication
        get :allegations
        get :result_publication
        get :proposals
      end
      resources :questions, only: [:show] do
        resources :answers, only: [:create]
      end
      resources :proposals do
        member do
          post :vote
          put :flag
          put :unflag
        end
        collection do
          get :map
          get :suggest
        end
      end
      resources :draft_versions, only: [:show] do
        get :go_to_version, on: :collection
        get :changes
        resources :annotations do
          get :search, on: :collection
          get :comments
          post :new_comment
        end
      end
    end
  end

  resources :users, only: [:show] do
    resources :direct_messages, only: [:new, :create, :show]
  end

  resource :account, controller: "account", only: [:show, :update, :delete] do
    get :erase, on: :collection
  end

  resources :notifications, only: [:index, :show] do
    put :mark_all_as_read, on: :collection
  end

  resources :proposal_notifications, only: [:new, :create, :show]

  resource :verification, controller: "verification", only: [:show]

  resources :communities, only: [:show] do
    resources :topics
  end

  scope module: :verification do
    resource :residence, controller: "residence", only: [:new, :create]
    resource :sms, controller: "sms", only: [:new, :create, :edit, :update]
    resource :verified_user, controller: "verified_user", only: [:show]
    resource :email, controller: "email", only: [:new, :show, :create]
    resource :letter, controller: "letter", only: [:new, :create, :show, :edit, :update]
  end

  resources :tags do
    collection do
      get :suggest
    end
  end

  namespace :admin do
    root to: "dashboard#index"
    resources :organizations, only: :index do
      get :search, on: :collection
      member do
        put :verify
        put :reject
      end
    end

    resources :hidden_users, only: [:index, :show] do
      member do
        put :restore
        put :confirm_hide
      end
    end

    resources :debates, only: :index do
      member do
        put :restore
        put :confirm_hide
      end
    end

    resources :proposals, only: :index do
      member do
        put :restore
        put :confirm_hide
      end
    end

    resources :spending_proposals, only: [:index, :show, :edit, :update] do
      member do
        patch :assign_admin
        patch :assign_valuators
      end

      get :summary, on: :collection
    end

    resources :budgets do
      member do
        put :calculate_winners
      end

      resources :budget_groups do
        resources :budget_headings do
        end
      end

      resources :budget_investments, only: [:index, :show, :edit, :update] do
        resources :budget_investment_milestones
        member { patch :toggle_selection }
      end
    end

    resources :signature_sheets, only: [:index, :new, :create, :show]

    resources :banners, only: [:index, :new, :create, :edit, :update, :destroy] do
      collection { get :search}
    end

    resources :comments, only: :index do
      member do
        put :restore
        put :confirm_hide
      end
    end

    resources :tags, only: [:index, :create, :update, :destroy]
    resources :officials, only: [:index, :edit, :update, :destroy] do
      get :search, on: :collection
    end

    resources :settings, only: [:index, :update]
    put :update_map, to: "settings#update_map"

    resources :moderators, only: [:index, :create, :destroy] do
      get :search, on: :collection
    end

    resources :valuators, only: [:index, :create, :destroy] do
      get :search, on: :collection
      get :summary, on: :collection
    end

    resources :managers, only: [:index, :create, :destroy] do
      get :search, on: :collection
    end

    resources :administrators, only: [:index, :create, :destroy] do
      get :search, on: :collection
    end

    resources :users, only: [:index, :show]

    scope module: :poll do
      resources :polls do
        get :booth_assignments, on: :collection
        patch :add_question, on: :member

        resources :booth_assignments, only: [:index, :show, :create, :destroy] do
          get :search_booths, on: :collection
          get :manage, on: :collection
        end

        resources :officer_assignments, only: [:index, :create, :destroy] do
          get :search_officers, on: :collection
          get :by_officer, on: :collection
        end

        resources :recounts, only: :index
        resources :results, only: :index
      end

      resources :officers do
        get :search, on: :collection
      end

      resources :booths do
        get :available, on: :collection

        resources :shifts do
          get :search_officers, on: :collection
        end
      end

      resources :questions, shallow: true do
        resources :answers, except: [:index, :destroy], controller: 'questions/answers', shallow: true do
          resources :images, controller: 'questions/answers/images'
          resources :videos, controller: 'questions/answers/videos'
          get :documents, to: 'questions/answers#documents'
        end
        post '/answers/order_answers', to: 'questions/answers#order_answers'
      end
    end

    resources :verifications, controller: :verifications, only: :index do
      get :search, on: :collection
    end

    resource :activity, controller: :activity, only: :show
    resources :newsletters, only: :index do
      get :users, on: :collection
    end
    resource :stats, only: :show do
      get :proposal_notifications, on: :collection
      get :direct_messages, on: :collection
      get :polls, on: :collection
    end

    namespace :legislation do
      resources :processes do
        resources :questions
        resources :proposals
        resources :draft_versions
      end
    end

    namespace :api do
      resource :stats, only: :show
    end

    resources :geozones, only: [:index, :new, :create, :edit, :update, :destroy]

    namespace :site_customization do
      resources :pages, except: [:show]

app/models/geozone.rb
class Geozone < ActiveRecord::Base

  include Graphqlable

  has_many :proposals
  has_many :spending_proposals
  has_many :debates
  has_many :users
  validates :name, presence: true

  scope :public_for_api, -> { all }

  def self.names
    Geozone.pluck(:name)
  end

  def self.city
    where(name: 'city').first
  end

  def safe_to_destroy?
    Geozone.reflect_on_all_associations(:has_many).all? do |association|
      association.klass.where(geozone: self).empty?
    end
  end
end

app/controllers/admin/legislation/proposals_controller.rb
class Admin::Legislation::ProposalsController < Admin::Legislation::BaseController
  load_and_authorize_resource :process, class: "Legislation::Process"
  load_and_authorize_resource :proposal, class: "Legislation::Proposal", through: :process

  def index
  end
end

app/controllers/admin/proposals_controller.rb
class Admin::ProposalsController < Admin::BaseController
  include FeatureFlags

  has_filters %w{without_confirmed_hide all with_confirmed_hide}, only: :index

  feature_flag :proposals

  before_action :load_proposal, only: [:confirm_hide, :restore]

  def index
    @proposals = Proposal.only_hidden.send(@current_filter).order(hidden_at: :desc).page(params[:page])
  end

  def confirm_hide
    @proposal.confirm_hide
    redirect_to request.query_parameters.merge(action: :index)
  end

  def restore
    @proposal.restore
    @proposal.ignore_flag
    Activity.log(current_user, :restore, @proposal)
    redirect_to request.query_parameters.merge(action: :index)
  end

  private

    def load_proposal
      @proposal = Proposal.with_hidden.find(params[:id])
    end

end

app/controllers/legislation/proposals_controller.rb
class Legislation::ProposalsController < Legislation::BaseController
  include CommentableActions
  include FlagActions

  load_and_authorize_resource :process, class: "Legislation::Process"
  load_and_authorize_resource :proposal, class: "Legislation::Proposal", through: :process

  before_action :parse_tag_filter, only: :index
  before_action :load_categories, only: [:index, :new, :create, :edit, :map, :summary]
  before_action :load_geozones, only: [:edit, :map, :summary]
  before_action :authenticate_user!, except: [:index, :show, :map, :summary]

  invisible_captcha only: [:create, :update], honeypot: :subtitle

  has_orders %w{confidence_score created_at}, only: :index
  has_orders %w{most_voted newest oldest}, only: :show

  helper_method :resource_model, :resource_name
  respond_to :html, :js

  def show
    super
    legislation_proposal_votes(@process.proposals)
    @document = Document.new(documentable: @proposal)
    if request.path != legislation_process_proposal_path(params[:process_id], @proposal)
      redirect_to legislation_process_proposal_path(params[:process_id], @proposal),
                  status: :moved_permanently
    end
  end

  def create
    @proposal = Legislation::Proposal.new(proposal_params.merge(author: current_user))

    if @proposal.save
      redirect_to legislation_process_proposal_path(params[:process_id], @proposal), notice: I18n.t('flash.actions.create.proposal')
    else
      render :new
    end
  end

  def index_customization
    load_successful_proposals
    load_featured unless @proposal_successful_exists
  end

  def vote
    @proposal.register_vote(current_user, params[:value])
    legislation_proposal_votes(@proposal)
  end

  private

    def proposal_params
      params.require(:legislation_proposal).permit(:legislation_process_id, :title,
                    :question, :summary, :description, :video_url, :tag_list,
                    :terms_of_service, :geozone_id,
                    documents_attributes: [:id, :title, :attachment, :cached_attachment, :user_id])
    end

    def resource_model
      Legislation::Proposal
    end

    def resource_name
      'proposal'
    end

    def load_successful_proposals
      @proposal_successful_exists = Legislation::Proposal.successful.exists?
    end

end

app/controllers/management/proposals_controller.rb
class Management::ProposalsController < Management::BaseController
  include HasOrders
  include CommentableActions

  before_action :only_verified_users, except: :print
  before_action :set_proposal, only: [:vote, :show]
  before_action :parse_search_terms, only: :index
  before_action :load_categories, only: [:new, :edit]
  before_action :load_geozones, only: [:edit]

  has_orders %w{confidence_score hot_score created_at most_commented random}, only: [:index, :print]
  has_orders %w{most_voted newest}, only: :show

  def show
    super
    @notifications = @proposal.notifications
    @related_contents = Kaminari.paginate_array(@proposal.relationed_contents).page(params[:page]).per(5)

    redirect_to management_proposal_path(@proposal), status: :moved_permanently if request.path != management_proposal_path(@proposal)
  end

  def vote
    @proposal.register_vote(managed_user, 'yes')
    set_proposal_votes(@proposal)
  end

  def print
    @proposals = Proposal.send("sort_by_#{@current_order}").for_render.limit(5)
    set_proposal_votes(@proposal)
  end

  private

    def set_proposal
      @proposal = Proposal.find(params[:id])
    end

    def proposal_params
      params.require(:proposal).permit(:title, :question, :summary, :description, :external_url, :video_url,
                                       :responsible_name, :tag_list, :terms_of_service, :geozone_id)
    end

    def resource_model
      Proposal
    end

    def only_verified_users
      check_verified_user t("management.proposals.alert.unverified_user")
    end

    def set_proposal_votes(proposals)
      @proposal_votes = managed_user ? managed_user.proposal_votes(proposals) : {}
    end

    def set_comment_flags(comments)
      @comment_flags = managed_user ? managed_user.comment_flags(comments) : {}
    end

end

app/controllers/moderation/base_controller.rb
class Moderation::BaseController < ApplicationController
  layout 'admin'

  before_action :authenticate_user!
  before_action :verify_moderator

  skip_authorization_check

  private

    def verify_moderator
      raise CanCan::AccessDenied unless current_user.try(:moderator?) || current_user.try(:administrator?)
    end

end

app/controllers/moderation/dashboard_controller.rb
class Moderation::DashboardController < Moderation::BaseController

  def index
  end

end

app/helpers/proposals_helper.rb
module ProposalsHelper

  def progress_bar_percentage(proposal)
    case proposal.cached_votes_up
    when 0 then 0
    when 1..Proposal.votes_needed_for_success then (proposal.total_votes.to_f * 100 / Proposal.votes_needed_for_success).floor
    else 100
    end
  end

  def supports_percentage(proposal)
    percentage = (proposal.total_votes.to_f * 100 / Proposal.votes_needed_for_success)
    case percentage
    when 0 then "0%"
    when 0..0.1 then "0.1%"
    when 0.1..100 then number_to_percentage(percentage, strip_insignificant_zeros: true, precision: 1)
    else "100%"
    end
  end

  def namespaced_proposal_path(proposal, options = {})
    @namespace_proposal_path ||= namespace
    case @namespace_proposal_path
    when "management"
      management_proposal_path(proposal, options)
    else
      proposal_path(proposal, options)
    end
  end

  def retire_proposals_options
    Proposal::RETIRE_OPTIONS.collect { |option| [ t("proposals.retire_options.#{option}"), option ] }
  end

  def empty_recommended_proposals_message_text(user)
    if user.interests.any?
      t('proposals.index.recommendations.without_results')
    else
      t('proposals.index.recommendations.without_interests')
    end
  end

  def author_of_proposal?(proposal)
    author_of?(proposal, current_user)
  end

  def current_editable?(proposal)
    current_user && proposal.editable_by?(current_user)
  end

end

app/views/moderation/proposals/hide.js.erb
var proposal_id = '<%= dom_id(@proposal) %>';
App.ModeratorProposals.add_class_faded(proposal_id);
App.ModeratorProposals.hide_moderator_actions(proposal_id);

app/views/moderation/proposals/index.html.erb
<h2><%= t("moderation.proposals.index.title") %></h2>

<%= render 'shared/filter_subnav', i18n_namespace: "moderation.proposals.index" %>

<div class="row">
  <h3 class="small-8 large-8 columns"><%= page_entries_info @proposals %></h3>
  <div class="small-4 large-4 columns">
    <div class="float-right">
      <%= t("moderation.proposals.index.order") %>
      <%= render 'shared/order_selector', i18n_namespace: "moderation.proposals.index" %>
    </div>
  </div>
</div>

<%= form_tag moderate_moderation_proposals_path(request.query_parameters), method: :put do %>
  <p class="js-check">
    <%= t('shared.check') %>:
    <%= link_to t('shared.check_all'), '#', data: {check_all: "proposal_ids[]"} %>
    |
    <%= link_to t('shared.check_none'), '#', data: {check_none: "proposal_ids[]"} %>
  </p>

  <table class="clear">
    <tr>
      <th>
        <%= t("moderation.proposals.index.headers.proposal") %>
      </th>
      <th>
       <%= t("moderation.proposals.index.headers.moderate") %>
      </th>
      <th>
        Aprobada
      </th>
      <th>
        Archivada
      </th>
    </tr>
    <% @proposals.each do |proposal| %>
      <tr id="proposal_<%= proposal.id %>">
        <td>
          <%= link_to proposal.title, proposal, target: "_blank" %>
          <br>
          <span class="date"><%= l proposal.updated_at.to_date %></span>
          <span class="bullet">&nbsp;&bull;&nbsp;</span>
          <%= proposal.flags_count %><span class="icon-flag flag-disable"></span>
          <span class="bullet">&nbsp;&bull;&nbsp;</span>
          <%= proposal.author.username %>
          <br>
          <div class="moderation-description">
            <%= proposal.description %>
          </div>
        </td>
        <td class="text-center">
          <%= check_box_tag "proposal_ids[]", proposal.id, nil, id: "#{dom_id(proposal)}_check" %>
        </td>
        <td class="text-center">
          <%= check_box_tag "id", proposal.id, proposal.is_approved, class: "chech_approve", disabled: proposal.is_archived %>
        </td>
        <td class="text-center">
          <%= check_box_tag "id", proposal.id, proposal.is_archived, class: "chech_archive", disabled: proposal.is_approved %>
        </td>
      </tr>
    <% end %>
  </table>

  <%= submit_tag t('moderation.proposals.index.block_authors'),
    name: "block_authors",
    class: "button hollow alert",
    data: {confirm: t('moderation.proposals.index.confirm')}
  %>

  <div class="float-right">
    <%= submit_tag t('moderation.proposals.index.hide_proposals'),
      name: "hide_proposals",
      class: "button hollow alert",
      data: {confirm: t('moderation.proposals.index.confirm')}
    %>
    <%= submit_tag t('moderation.proposals.index.ignore_flags'),
      name: "ignore_flags",
      class: "button hollow",
      data: {confirm: t('moderation.proposals.index.confirm')}
    %>
  </div>

  <%= paginate @proposals %>

<% end %>

<script>
  $(function(){
    var alertSuccessHtml = '<div data-closable class="callout notice-container success radius" style="position:fixed">';
    alertSuccessHtml += 'La propuesta ha sido actualizada';
    alertSuccessHtml += '<button class="close-button" aria-label="Dismiss alert" type="button" data-close>';
    alertSuccessHtml += '<span aria-hidden="true">&times;</span>';
    alertSuccessHtml += '</button>';
    alertSuccessHtml += '</div>';

    var alertErrorHtml = '<div data-closable class="callout notice-container error radius" style="position:fixed">';
    alertErrorHtml += 'No fue posible actualizar la propuesta';
    alertErrorHtml += '<button class="close-button" aria-label="Dismiss alert" type="button" data-close>';
    alertErrorHtml += '<span aria-hidden="true">&times;</span>';
    alertErrorHtml += '</button>';
    alertErrorHtml += '</div>';

    $('.chech_approve').on('change', function(){
      var $this = $(this);
      var data = {
        proposal: {}
      };
      data.proposal.id = $this.val();
      data.proposal.is_approved = $this.is(':checked');

      if(data.proposal.is_approved){
        $this.parent().parent().find('.chech_archive').attr("disabled", true);
      }

      $.ajax({
        data: data,
        dataType: 'json',
        url: '/proposals/' + data.proposal.id + '/approve',
        method: 'POST',
        success: function(doc){
          console.log('success');
          if(!data.proposal.is_approved){
            $this.parent().parent().find('.chech_archive').removeAttr("disabled");
          }
          $('body').append(alertSuccessHtml);
        },
        error: function(err){
          $('body').append(alertErrorHtml);
          if(data.proposal.is_approved){
            $this.parent().parent().find('.chech_archive').removeAttr("disabled");
          }
          console.log('error', err.responseText);
        }
      })

    });

    $('.chech_archive').on('change', function(){
      var $this = $(this);
      var data = {
        proposal: {}
      };
      data.proposal.id = $this.val();
      data.proposal.is_archived = $this.is(':checked');

      if(data.proposal.is_archived){
        $this.parent().parent().find('.chech_approve').attr("disabled", true);
      }

      $.ajax({
        data: data,
        dataType: 'json',
        url: '/proposals/' + data.proposal.id + '/archive',
        method: 'POST',
        success: function(doc){
          console.log('success');
          if(!data.proposal.is_archived){
            $this.parent().parent().find('.chech_approve').removeAttr("disabled");
          }
          $('body').append(alertSuccessHtml);
        },
        error: function(err){
          $('body').append(alertErrorHtml);
          if(data.proposal.is_archived){
            $this.parent().parent().find('.chech_approve').removeAttr("disabled");
          }
          console.log('error', err.responseText);
        }
      })

    });
  });
</script>